"""Calibrate from user data (click logs, role feedback) and collect synonym candidates.

Data formats (provided by the user; nothing here ships with data):

``clicks.tsv`` — one row per query/click pair::

    query ⇥ clicked candidate name ⇥ count (default 1) ⇥ vertical (optional)

``role_feedback.tsv`` — human or log-derived role labels::

    query ⇥ span text ⇥ ROLE ⇥ count (default 1)

Outputs are plugin files (``sense_prior.tsv``) or suggestions to review
(``rules.yaml`` priors, a synonym review queue in markdown). Nothing is applied
automatically.
"""

from __future__ import annotations

import math
from collections import defaultdict
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hanchi.analyzer import Analyzer


@dataclass(frozen=True)
class Click:
    query: str
    clicked: str
    count: float = 1.0
    vertical: str = ""


@dataclass(frozen=True)
class RoleLabel:
    query: str
    span: str
    role: str
    count: float = 1.0


def _rows(path: str | Path) -> Iterable[list[str]]:
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            yield [c.strip() for c in line.split("\t")]


def read_clicks(path: str | Path) -> list[Click]:
    out = []
    for r in _rows(path):
        count = float(r[2]) if len(r) > 2 and r[2] else 1.0
        out.append(Click(r[0], r[1], count, r[3] if len(r) > 3 else ""))
    return out


def read_role_feedback(path: str | Path) -> list[RoleLabel]:
    out = []
    for r in _rows(path):
        count = float(r[3]) if len(r) > 3 and r[3] else 1.0
        out.append(RoleLabel(r[0], r[1], r[2].upper(), count))
    return out


# --- sense priors from clicks ------------------------------------------------------


@dataclass(frozen=True)
class SensePrior:
    variant: str
    sense_id: str
    prior: float
    vertical: str
    clicks: float


def sense_prior_from_clicks(
    analyzer: Analyzer, clicks: Iterable[Click], smoothing: float = 1.0
) -> list[SensePrior]:
    """For each query word with several senses, which sense did the clicked result match?

    The clicked name is ranked against the query alone; the sense of the best reading
    is the one the click supports. Priors are additive-smoothed per (word, vertical).
    """
    counts: dict[tuple[str, str], dict[str, float]] = defaultdict(lambda: defaultdict(float))
    for c in clicks:
        analysis = analyzer.analyze(c.query)
        homonyms = {
            s.norm.replace(" ", ""): {h.sense_id for h in s.hypotheses if h.sense_id}
            for s in analysis.spans
        }
        homonyms = {k: v for k, v in homonyms.items() if len(v) > 1}
        if not homonyms:
            continue
        result = analyzer.rank(analysis, [c.clicked]).results[0]
        if result.score <= 0 or result.sense_id is None:
            continue
        for word, senses in homonyms.items():
            for sid in senses:
                counts[(word, c.vertical)][sid] += 0.0  # make every sense present
            if result.sense_id in senses:
                counts[(word, c.vertical)][result.sense_id] += c.count
    out = []
    for (word, vertical), by_sense in sorted(counts.items()):
        total = sum(by_sense.values())
        if total <= 0:
            continue
        n = len(by_sense)
        for sid, k in sorted(by_sense.items()):
            prior = (k + smoothing) / (total + smoothing * n)
            out.append(SensePrior(word, sid, round(prior, 4), vertical, k))
    return out


def write_sense_prior(path: str | Path, priors: Sequence[SensePrior]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# variant\tsense_id\tprior\tvertical   (generated by hanchi learn from clicks)"]
    for p in priors:
        lines.append(
            f"{p.variant}\t{p.sense_id}\t{p.prior:g}" + (f"\t{p.vertical}" if p.vertical else "")
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# --- role prior suggestions from labels --------------------------------------------


def role_prior_suggestions(
    analyzer: Analyzer, labels: Iterable[RoleLabel], smoothing: float = 1.0
) -> dict[str, float]:
    """Suggested ``rules.yaml: priors`` so predicted role mass moves toward the labels.

    For each role: ``current prior + log((observed + s) / (predicted + s))``, where
    *predicted* is the total probability the analyzer gives that role on the labelled
    spans. A starting point to review, not a fitted model.
    """
    observed: dict[str, float] = defaultdict(float)
    predicted: dict[str, float] = defaultdict(float)
    for lab in labels:
        try:
            span = analyzer.analyze(lab.query).span(lab.span)
        except KeyError:
            continue
        observed[lab.role] += lab.count
        for h in span.hypotheses:
            predicted[h.role] += h.p * lab.count
    current = analyzer.resources.rules.get("priors", {})
    roles = sorted(set(observed) | set(predicted))
    return {
        r: round(
            float(current.get(r, 0.0))
            + math.log((observed[r] + smoothing) / (predicted[r] + smoothing)),
            3,
        )
        for r in roles
    }


# --- synonym / hypernym candidates (§12.7) -------------------------------------------


@dataclass(frozen=True)
class SynonymCandidate:
    a: str
    b: str
    similarity: float


def synonym_candidates(
    terms: Sequence[str],
    embed: Callable[[Sequence[str]], Sequence[Sequence[float]]],
    threshold: float,
    top_k: int,
) -> list[SynonymCandidate]:
    """Pairs of terms whose embeddings are similar (cosine ≥ threshold), best first."""
    vecs = embed(list(terms))
    norms = [math.sqrt(sum(x * x for x in v)) or 1.0 for v in vecs]
    out = []
    for i in range(len(terms)):
        for j in range(i + 1, len(terms)):
            sim = sum(x * y for x, y in zip(vecs[i], vecs[j], strict=True)) / (norms[i] * norms[j])
            if sim >= threshold:
                out.append(SynonymCandidate(terms[i], terms[j], round(sim, 4)))
    out.sort(key=lambda c: -c.similarity)
    return out[:top_k]


def write_synonym_review(path: str | Path, cands: Sequence[SynonymCandidate], source: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Synonym / hypernym candidates ({source})",
        "",
        "Review each pair. Same meaning → add to synonyms.tsv (sense ids); one is broader →",
        "hypernyms.tsv (child ⇥ parent). Nothing here is applied automatically.",
        "",
        "| a | b | similarity | decision |",
        "|---|---|---|---|",
    ]
    lines += [f"| {c.a} | {c.b} | {c.similarity:.3f} |  |" for c in cands]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
